### ISSUE TITLE
Volume bars to indicate how many times an endpoint is hit

### ISSUE THREAD

**Issue by stefandyke** [cncf/apisnoop#30]
The current sunburst visualisation does not provide any indication of the volume of hits an endpoint receives meaning there is no easy way to prioritise or make decisions about where effort needs to be spent.

Adding a volume indicator to the sunburst allows us to identify which endpoints are receiving the most hits from the test suite (and apps in the future) and will allow prioritisation of effort, in particular if an app is hitting non-tested/confirmant endpoints.

Further options once volume data can be charted could include filtering and/or sorting the sunburst by the volume information (a future consideration).

An approach for the volume bars is shown below:

![volume_indicators](https://user-images.githubusercontent.com/42525114/44434004-fe349280-a5fc-11e8-811e-4de7a545d3c9.png)

**Comment by zachmandeville** [comment]
We are planning to do a visualization similar to this, but based on how many apps are using this endpoint--which is slightly different than how many times it is hit.  We are closing this issue just to avoid confusion on what we are trying to do, but are retaining the design sketches because it is good work!
