### ISSUE TITLE
APISnoop update PR loop

### ISSUE THREAD

**Issue by Riaankl** [cncf/apisnoop#679]
GHA trigger the creating of another PR everytime a PR is merged that update the coverage.

**Comment by cooldracula** [comment]
I think this is due to the [dispatch triggers for our apisnoop updater job](https://github.com/cncf/apisnoop/blob/47807bce44855bdb9d92f0cd208c5d8a4d4e1c0f/.github/workflows/apisnoop_weekly_updater.yml#L3).  It's set to run weekly AND on every push to a coverage/*.json file.  That last one will cause a loop.

I opened up pr #678 to address this.  With this merged, it will only update on Saturdays.

**Comment by Riaankl** [comment]
Ran the GHA after https://github.com/cncf/apisnoop/pull/678 merged and the loop appear to be solved
Thank you @zachmandeville
