### ISSUE TITLE
Update to pull latest job data for bucket

### ISSUE THREAD

**Issue by hh** [cncf/apisnoop#69]
The latest job ids should be pulled semi-regularly, and the new audit logs processed and pushed.

- [x] Setup daily job to run the following for master
- [x] Run --update-sources (will update data-gen/sources.yaml)
- [x] Run --update-cache, --process-cache, --upload-results (create apisnoops and upload to GCS)
- [ ] If the above is successful, update or create a branch w/ a PR for updated sources.yaml

**Comment by devaii** [comment]
Yesterday, I wrote a script for doing these tasks, which can be run as a cron job.  Some modifications to `apisnoop.sh` were required. (See https://github.com/cncf/apisnoop/pull/110)

Ran into some issues: The python scripts for processing the audit logs expect [relative paths from within the repo](https://github.com/cncf/apisnoop/blob/05a0a61996f1cd73b51cb2e6d0d5293759665dec/data-gen/processArtifacts.py#L54), which is asking for problems.

Instead of running these scripts directly, I am going to make a docker image, and have the cron do a `docker run ...`. This will be cleaner and scale better moving forward.

**Comment by devaii** [comment]
Daily cronjobs are now set for dev, and staging. Will run prod manually a few times before setting it for daily runs next week.

I'm going to put the sources.yaml auto-PR in to a ticket of its own.
Noting that we also need a solution for automating the process of updating the back-end once there is new data in the buckets. Will put that in a separate issue, as well.
