### ISSUE TITLE
Dynamic Audit Collection for APISnoop

### ISSUE THREAD

**Issue by hh** [cncf/apisnoop#99]
TLDR: ```kubctl apply -f apisnoop-collector.yaml ; kubectl cp apisnoop:audit.log .```

```cucumber
As a developer of an application in Kubernetes
In order to understand what APIs are in use by my KAPIC
I want to easily generate audit logs for loading into APISnoop

Given an existing kubernetes cluster
When when I "kubectl apply -f https://url.to/apisnooping.yaml"
Then I can run "kubectl cp apisnoop:audit.log ."
And provide the audit.log as input to APISnoop
```

**Comment by zachmandeville** [comment]
We've updated how apisnoop loads its data quite significantly, where you can run a small sql command to grab audit data from a specific bucket and job.  Currently this bucket and job is expected to be stored by testgrid at a specific url, but we could potentially adjust this to be more dynamic.  Regardless, am closing htis due to staleness and that the direction of apisnoop may have changed from where this would be relevant.  You can see our roadmap here: https://github.com/cncf/apisnoop/blob/master/org/roadmap.org
